name: npm-publish

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      node_version:
        description: 'node版本'
        type: choice
        default: '18'
        options:
          - '16'
          - '18'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 安装Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{github.event.inputs.node_version}}
          registry-url: https://registry.npmjs.org

        # 设置pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      # 根据pnpm-lock.yaml文件中的版本安装依赖，且锁定该文件
      - name: Install Dependencies
        run: pnpm i

      - name: Build Dist
        run: pnpm build

      - name: publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
